### ISSUE TITLE
Prometheus config additional labels

### ISSUE THREAD

**Issue by malhussan** [softwarefactory-project/dhall-prometheus#1]
Labels are currently limited to "severity" and "lasttime" which might be the only logical labels used for Prometheus alerting, but it would be really great if it's expanded to any key value pairs as in Prometheus static_config.

**Comment by TristanCacqueray** [comment]
That's indeed an issue, I'll update the schemas to use the JSON/Type for labels. Thank you for the feedback.

**Comment by TristanCacqueray** [comment]
@malhussan sorry for the delay, for some reason I didn't get the notification. I moved the project to a new organization and refreshed the content, https://github.com/softwarefactory-project/dhall-prometheus/pull/2 should enable using additional labels. Please let me know if that works for you.

**Comment by malhussan** [comment]
> @malhussan sorry for the delay, for some reason I didn't get the notification. I moved the project to a new organization and refreshed the content, #2 should enable using additional labels. Please let me know if that works for you.

@TristanCacqueray Sorry for the late response from my side! I tested the change on the severity label as well and it works great. Thank you!

**Comment by TristanCacqueray** [comment]
Alright, we'll merge the PR soon then. Thank you for the feedback!
